### PR TITLE
V2.5.0 dev convert to ajax

### PR DESCRIPTION
**Pull request by TomW1605**
convert the home page from using a html refresh tag to refresh the whole page, to using ajax to just refresh the job list

### CODE REVIEW

**Comment by 1337-server** [comment]
Great feature addition! Could you possibly change this to use/call the [json app.route](https://github.com/1337-server/automatic-ripping-machine/blob/f59bf78566a6fa1a830e00cbac699322bef211a3/arm/ui/routes.py#L274)  ?

I think in the long term its better to use 1 app route for all json/ajax calls. It keeps it all in one place so you know where the code is, makes things easier to find/read later. If youre not able, i can do this. just let me know.

**Comment by TomW1605** [comment]
ok i will have a look

**Comment by TomW1605** [comment]
so i have had a look and i think this is better off as a separate route. it would take a lot more processing and code on the client side to parse the json back into something that can be displayed and a decent amount of work on the server side to generate a json job list. the current method for doing this omits several bits of info that are essential for the ui.

**Comment by TomW1605** [comment]
@1337-server do you think we could merge this and then convert to using the json page later? the longer this waits the more issues and conflicts will come up. this id much better than the full page reload method so while it might not be perfect it should probably be merged soon.

**Comment by 1337-server** [comment]
Ive not tested this yet, i've been really busy. Ive got some time free this weekend, so ill check it then.

**Comment by TomW1605** [comment]
ok great. if it helps i have been using it for the past week and not had any issues

**Comment by 1337-server** [comment]
Going to close this now as this feature has been added in a jsonified version.

Thanks for your work on this!

**Pull request closed without merging**
