### PR TITLE
Added - Multiple URLs using TLS

### PR DESCRIPTION
**Pull request by BarryHuffman**
To improve overall privacy/security. Also fixed some minor 404 redirects.

I'm hoping this is the active branch?

While the CONTRIB reference states using the "v2_fixes" branch it seems largely stale?

### CODE REVIEW

**Comment by BarryHuffman** [comment]
@shitwolfymakes Could you review/assist please? I'm not familiar with the proper procedure.

**Comment by shitwolfymakes** [comment]
I'm not a maintainer or anything, I'm just a guy sharing what worked for me. 

I can't approve or merge, but I'd recommend fixing the errors that the automation tools are reporting. It looks like secure security implementation might be flawed. Once you've got that fixed, I'd be happy to give your code a sanity check!

**Comment by BarryHuffman** [comment]
By reverting the changes in utils.py it now passes correctly.

**Comment by shitwolfymakes** [comment]
Oh, by the PR title I thought you were implementing TLS for connections to ARM. It looks like all you're doing here is changing urls to `https` from `https`. As long as the api calls still return properly over https I can't see a reason to not merge this.

Two things though:

1. Please change the title of the PR to better reflect what you're doing here
2. Please test the new APIs and let us know if they work the same as the current branch

This is a solid first PR!

**Comment by BarryHuffman** [comment]
In that case I'll wait till the devel branch settles with your forks proposed changes to re-open the PR. 
I'm also working an updated Debian installer for the wiki.

**Pull request closed without merging**
