### PR TITLE
Leveraging arm-dependencies repo

### PR DESCRIPTION
**Pull request by shitwolfymakes**
## Overview
This PR leverages a repo I built for three things:
1. Codify the requirements for ARM such that all forks automatically receive changes as soon as the `requirements.txt` is updated
2. Decrease the time it takes to build docker images of ARM
3. Provide a single docker container that contains all the requirements needed for ARM

The [`arm-dependencies`](https://github.com/shitwolfymakes/arm-dependencies) repo now stores the definitive `requirements.txt` for ARM, with documentation. To leverage this, ARM now imports the repo as a [git submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) and the `requirements.txt` refers to the one in the submodule.

Additionally, `arm-dependencies` builds a container every push and every night at midnight containing all the requirements (OS, python, and Handbrake/MakeMKV) needed by an ARM image, which also adds another layer of defense against the expired beta key issue. The Dockerfile I'm working on leverages the `arm-dependencies` image as it's base image, and my build times have decreased more than 75% as a result of not having to install dependencies every build. 

## Changelog
- Moved all common dependencies to a single, authoritative repo
- Added git submodule [`arm-dependencies`](https://github.com/shitwolfymakes/arm-dependencies)
- `requirements.txt` now references the requirements file in the submodule
- Updated all install scripts to include the submodule in the clone command

## Next Steps
When cloning the repo, you now need to do `git clone --recurse-submodules <repo_name>`. Wiki pages need to be updated to account for that.

### CODE REVIEW

**Comment by shitwolfymakes** [comment]
Hold off on merging this, the submodule is not automatically updated on each pull yet

**Comment by 1337-server** [comment]
My only problem with this is that it links externally, meaning if there is a break in the chain (It has happened before with dockerhub), the whole project dies. It also makes things harder for the end user to fix if there is ever a problem with the first build. I think it's a far better solution to have it all connected to 1 Dockerfile.

The quicker build time is fantastic for dev, but this won't really affect the end users as they are only going to be building it once. Or pulling from an already compiled image.

**Comment by shitwolfymakes** [comment]
Chain breakage isn't actually much of a problem here, as I already have GitHub Pro and it's a public repo (and hence not subject to Actions minute limitations). The real potential issues here are twofold:
- Bus factor. This is solved by adding you to the repo as a maintainer, which will happen once the dependency repo is adopted. This is also why the original ARM repo is effectively dead at this point.
- Updating the requirements. This is a non-issue, as adopters can test new dependencies by adding the name and version to their requirements file after the line installing the requirements in the submodule. I can write up contributing docs for that later.

The biggest win here is that the repo provides an authoritative list of ARM's OS and python dependencies, and it can be leveraged by all 14 forks of this fork, and all 200+ forks of the original repo (once this branch is merged into the upstream). By volume it'll help more people than just you or me, and it'll make dev's lives easier, and let us focus on bugfixing and feature addition. 

I've also written all the GitHub Actions to be user-agnostic, so they do not need to be changed when the repo is forked. So if I get hit by a bus before you are added as a maintainer, you can fork the repo, add your DockerHub username and token as secrets, and you're good to go! This will also be covered in the contributing docs.

**Comment by shitwolfymakes** [comment]
Hooks have been added to try to update dependencies from `arm-dependencies/main` 1) after every pull, and 2) before every push

Also added a script to symlink them into the .git directory.

**Comment by 1337-server** [comment]
Ping and let me know when this is ready

**Comment by 1337-server** [comment]
I've forked the repo, I also forked it for the automatic ripping machine organization, but if it's going in the A.R.M it's most likely better being put as the main repo there to save any issues. So I removed it from the A.R.M org until I can hear back from someone there.

**Comment by shitwolfymakes** [comment]
Thanks, but if you can get me added to the ARM org, I can just transfer the original repo there so we don't have to deal with forking

**Comment by 1337-server** [comment]
Sorry, I missed your reply. I'm sadly still waiting for a response from them about getting write permissions for the main repo, so I can close issues and merge or close the PR's. But I still haven't heard anything back, when I do, I'll ask about it

**Comment by shitwolfymakes** [comment]
Copy, thanks

**Comment by 1337-server** [comment]
So is this ready to be merged ?

**Comment by shitwolfymakes** [comment]
Not ready yet

**Pull request closed without merging**
